urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views as auth_views


#Enable the admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^admin/musicians/report/$', 'arkansassymphony.musicians.admin_views.report'),
	(r'^admin/checkin/patron/(?P<id>[\d]+)/go', 'arkansassymphony.checkin.admin_views.go'),
	(r'^admin/', include(admin.site.urls)),
	(r'^about/jobs/', include('arkansassymphony.jobs.urls')),
	(r'^accounts/login/$', 'django.contrib.auth.views.login'),
	(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
	(r'^insider/signup$', direct_to_template, {'template': 'connect/enews_signup.html'}),
	(r'^insider/social$', direct_to_template, {'template': 'connect/enews_social.html'}),
)

urlpatterns += patterns('arkansassymphony.views',
	(r'^$', 'mainPage'),
	(r'^(?i)pick3/$', 'pick2'),
	(r'^(?i)guild/$', 'pick2guild'),
	(r'^longterm/$', 'loyalty'),
	(r'^thanks/$', direct_to_template, {'template': 'thanks.html'}), 
	(r'^(?i)season/$', 'season'),
	(r'^summer-strings$', direct_to_template,  {'template': 'summer_strings.html'}),
	(r'^youth-rock$', direct_to_template,  {'template': 'youthrock.html'}),
	(r'^renovation$', direct_to_template, {'template': 'concerts/renovation_faq.html'}),
	(r'^street-party$', direct_to_template, {'template': 'bbj_party.html'}),
	(r'^guarantee$', direct_to_template, {'template': 'concerts/guarantee.html'}),
	(r'^drive$', direct_to_template, {'template': 'concerts/drive.html'}),
	(r'^ccg-composer-contest$', direct_to_template, {'template': 'ccg_contest.html'}),
)

urlpatterns += patterns('arkansassymphony.registration.views',
    url(r'^asyo/register/', 'register_user'),
    url(r'^asyo/members/', 'members_area'),
    url(r'^asyo/admin/', 'admin_area'),
    url(r'^asyo/student/','register_student'),
    url(r'^asyo/update/p/(?P<parent>\d+)/$', 'update_parent'),
    url(r'^asyo/update/s/(?P<student>\d+)/$', 'update_student'),
    url(r'^asyo/delete/s/(?P<student>\d+)/$', 'delete_student'),
    url(r'^asyo/application/(?P<student>\d+)/$', 'student_application'),
    url(r'^asyo/update/app/(?P<id>\d+)/$', 'update_app'),
    url(r'^asyo/delete/app/(?P<id>\d+)/$', 'delete_app'),
    url(r'^asyo/logout/', 'logout_user'),
    url(r'^asyo/appadminjson/$', 'app_admin_json'),
    url(r'^asyo/appjson/$', 'app_json'),
    url(r'^asyo/studentjson/$', 'student_json'),
    url(r'^asyo/parentjson/$', 'parent_json'),
)

urlpatterns += patterns('arkansassymphony.designerhouse.views',
	url(r'^designer-house/$', 'designer_main', name='designer_main'),
	url(r'^designer-house/about/$', 'about_view', name='about_view'),
	url(r'^designer-house/sponsors/$', 'sponsor_view', name='sponsor_view'),
	url(r'^designer-house/designers/$', 'designer_view', name='designer_view'),
	url(r'^designer-house/tickets/$', 'tickets_view', name='tickets_view'),
	url(r'^designer-house/(?P<party_url>[\w-]+)/$', 'party_view', name='party_view'),
)

urlpatterns += patterns('arkansassymphony.checkin.form_views',
	url(r'^checkin$', 'patron_formview', name="patron_formview"),
	url(r'^charge/$', 'charge_formview', name="charge_formview"),
)

urlpatterns += patterns('arkansassymphony.donation.form_views',
	url(r'^donate$', 'donation_formview', name='donation_formview'),
	url(r'^donate/$', 'donation_formview', name='donation_formview'),
	url(r'^support$', 'donation_formview', name='donation_formview'),
	url(r'^support/$', 'donation_formview', name='donation_formview'),
)

#rsvp form urls
urlpatterns += patterns('arkansassymphony.rsvp.form_views',
	url(r'^rsvp$', 'RSVP_formview', name='RSVP_formview'),
	url(r'^rsvp/$', 'RSVP_formview', name='RSVP_formview'),
)

#rsvp data urls
urlpatterns += patterns('arkansassymphony.rsvp.views',
	url(r'^rsvp/rsvp-info$', 'rsvp_info', name='rsvp_info'),
	url(r'^rsvp/rsvp-info/$', 'rsvp_info', name='rsvp_info'),
)

urlpatterns += patterns('arkansassymphony.galleries.views',	
	url(r'^connect/media$', direct_to_template, {'template': 'gallery/media-page.html'}),
	url(r'^connect/media/(?P<media_type>[\w-]+)$', 'galleries_view', name='galleries_views'),
	url(r'^connect/media/galleries/(?P<gallery_url>[\w-]+)', 'photos_view', name='photos_view'),
	url(r'^connect/media/galleries/(?P<gallery_url>[\w-]+)/(?P<photo_name>\file)$', 'single_photo', name='single_photo'),
)


urlpatterns += patterns('',
	(r'^concerts/benefits/', direct_to_template, {'template': 'concerts/benefits.html'}),
	(r'^concerts/groups/', direct_to_template, {'template': 'concerts/groups.html'}),
	(r'^concerts/pricingseating/', direct_to_template, {'template': 'concerts/pricingseating.html'}),
	(r'^concerts/donate/', direct_to_template, {'template': 'concerts/donate.html'}),
	(r'^concerts/boxoffice/', direct_to_template, {'template': 'concerts/boxoffice.html'}),
	
	
	(r'^themusic/musicdirector/', direct_to_template, {'template': 'themusic/musicdirector.html'}),
	(r'^themusic/associate/', direct_to_template, {'template': 'themusic/associate.html'}),
	(r'^themusic/talks/', direct_to_template, {'template': 'themusic/talks.html'}),
	(r'^themusic/$', direct_to_template, {'template': 'themusic/themusic.html'}),
	
	
	(r'^support/opusball/', direct_to_template, {'template': 'support/opusball.html'}),
	(r'^support/corporate/', direct_to_template, {'template': 'support/corporate.html'}),
	(r'^support/foundation/', direct_to_template, {'template': 'support/foundation.html'}),
	(r'^support/volunteer/', direct_to_template, {'template': 'support/volunteer.html'}),
	(r'^support/benefits/', direct_to_template, {'template': 'support/benefits.html'}),
	#(r'^support/$', direct_to_template, {'template': 'support/support.html'}),
	#(r'^support/designerhouse/$', direct_to_template, {'template': 'support/designerhouse.html'}),	


	(r'^education/youngartist/$', direct_to_template, {'template': 'education/youngartist.html'}),	
	(r'^education/youthorchestras/johnjarboe/', direct_to_template, {'template': 'education/johnjarboe.html'}),
	(r'^education/youthorchestras/caseybuck/', direct_to_template, {'template': 'education/caseybuck.html'}),
	(r'^education/youthorchestras/jameshatch/', direct_to_template, {'template': 'education/jameshatch.html'}),
	(r'^education/youthorchestras/tommcdonald', direct_to_template, {'template': 'education/tommcdonald.html'}),
	(r'^education/youthorchestras/$', direct_to_template, {'template': 'education/youthorchestras.html'}),
	(r'^education/auditions/$', direct_to_template, {'template': 'education/auditioninfo.html'}),
	(r'^education/artspartners/', direct_to_template, {'template': 'education/artspartners.html'}),
	(r'^education/quartet-visits/', direct_to_template, {'template': 'education/artspartners.html'}),
	(r'^education/orchestraandyou/', direct_to_template, {'template': 'education/orchestraandyou.html'}),
	(r'^education/chilrensconcerts/', direct_to_template, {'template': 'education/childrensconcertshtml'}),
	(r'^education/childrensconcerts/', direct_to_template, {'template': 'education/childrensconcerts.html'}),
	(r'^education/$', direct_to_template, {'template': 'education/programs.html'}),
	(r'^education/stringdrive/', direct_to_template, {'template': 'education/stringdrive.html'}),
		

	(r'^(?i)offers/combo/$', direct_to_template, {'template': 'concerts/mw_combo.html'}),	
	(r'^(?i)offers/mw1/$', direct_to_template, {'template': 'concerts/mw1_offer.html'}),
	(r'^(?i)offers/ch1/$', direct_to_template, {'template': 'concerts/ch1_offer.html'}),
	(r'^(?i)offers/p1/$', direct_to_template, {'template': 'concerts/pops1_offer.html'}),
	(r'^(?i)offers/mw2/$', direct_to_template, {'template': 'concerts/mw2_offer.html'}),
	(r'^(?i)offers/ch2/$', direct_to_template, {'template': 'concerts/ch2_offer.html'}),
	(r'^(?i)offers/mw3/$', direct_to_template, {'template': 'concerts/mw3_offer.html'}), 
	(r'^(?i)offers/inc1/$', direct_to_template, {'template': 'concerts/inc1_offer.html'}), 
)
#teacher urls
urlpatterns += patterns('arkansassymphony.teachers.views',
	url(r'^education/teachers/$', 'teacher_view', name="teacher_view"),
)

#venue urls
urlpatterns += patterns('arkansassymphony.venue.views',
	url(r'^venue/$', 'venue_landing', name="venue_landing"),
	url(r'^visit/$', 'venue_landing', name="venue_landing"),
	url(r'^venue/(?P<venue_url>[\w-]+)/', 'venue_view', name="venue_view"),
)
	
#Musicians' portal urls
urlpatterns += patterns('arkansassymphony.musicians.views',
	url(r'^musicians/$', 'musician_portal', name="musician_portal"),
	url(r'^musicians/information/$', 'information', name="information"),
	url(r'^musicians/concert-info/$', 'concert_info', name="concert_info"),
	url(r'^musicians/concert-info/(?P<concert_name>[\w-]+)/', 'concert_view', name="concert_view"),
	url(r'^musicians/info/', 'info', name="info"),
	url(r'^musicians/wage-chart/', 'wage_info', name="wage_info"),
	url(r'^musicians/faq/', 'faq', name="faq"),
	url(r'^musicians/MA/ma-contents/$', 'ma_contents', name="ma_contents"),
	url(r'^musicians/MA/(?P<part>\d+)/', 'ma', name="ma"),
	url(r'^musicians/calendars/$', 'calendars', name="calendars"),
	url(r'^musicians/calendars/reservations/', 'reservations', name="reservations"),
	url(r'^musicians/contact/$', 'contact', name="contact"),
	url(r'^musicians/staff-contact/$', 'staff_contact', name="staff_contact"),
	url(r'^musicians/forms/$', 'forms', name="forms"),
	url(r'^musicians/hr/$', 'hr', name="hr"),
	url(r'^musicians/musician-forms/$', 'musician_forms', name="musician_forms"),
	url(r'^musicians/venues/$', 'venues', name="venues"),
	url(r'^musicians/venues/(?P<venue_url>[\w-]+)/', 'venue_detail', name="venue_detail"),
	url(r'^musicians/bus-info/$', 'bus_info', name="bus_info"),
)

#musician site form urls
urlpatterns += patterns('arkansassymphony.musicians.form_views',
	#"submitted" redirect
	url(r'^musicians/forms/contact/thanks/$', 'thanks', name="thanks"),
	#actual forms here
	url(r'^musicians/forms/byrne-request/$', 'byrne_form', name="byrne_form"),

jobs/models.py
from django.db import models



class Job(models.Model):
	TYPE_CHOICES = (
	        ('admin', 'admin'),
	        ('orchestra', 'orchestra'),
		)

	type = models.CharField(max_length=10, choices=TYPE_CHOICES)
	active = models.BooleanField()
	title = models.CharField(max_length=100)
	posted = models.DateField()
	description = models.TextField(null=True, blank=True)
	url_name = models.SlugField(max_length=100)
	

	def __unicode__(self):
		return "%(title)s" % {'title': self.title}
	
	class Meta:
		ordering = ('posted',)
        

forms.py
from django import forms

class LoyaltyForm(forms.Form):
	name = forms.CharField(max_length=100, label='Your Name')
	email = forms.EmailField(required = False, label='Your Email')
	yearsSubscribed = forms.CharField(widget=forms.Textarea, required=False, label='How many years have you been an ASO season ticket subscriber?')
	improve = forms.CharField(widget=forms.Textarea, required=False, label='In a few words, what can we do to improve your symphony experience?')
	favorite = forms.CharField(widget=forms.Textarea, required=False, label='What was your all-time favorite Pops concert?  Masterworks?')

templates/stockphoto/gallery_detail.html
{% extends "connect/connect_base.html" %}
{% block title_detail %} {{ gallery.title }}
{% endblock %}


{% block post_nav %}

 <td width="700" valign="top">
                <div id="content">
                        <br><br>


{% if gallery %}
<div style="font-size: 24px; margin-bottom: 5px;">{{ gallery.title }}</div><br>
<a href="/connect/photos/upload/{{ gallery.id }}/" class="orange">Upload Your Own Photo</a>
<br>
<br> 
<br>

<div id="thumbnail-box">
<ul id="thumbnails">
{% for item in photoList.all %}
<li>
  <div class="small-image-box">
    <a href="../detail/{{ item.id }}">
      <img src="{{ item.thumburl }}"
           alt="{{ item.title }}" />
    </a>
  </div>
</li>                  
{% endfor %}
</ul>
</div>
{% else %}
{% endif %}
<br><br>
{% ifnotequal previous -1 %}
<div style="float: left">
<a href="/connect/photos/{{ gallery.id }}/?start={{ previous }}" class="orange">
  <span>&laquo;  Previous </span></a>
</div>
{% endifnotequal %}
{% ifnotequal next -1 %}
<div style="float: right;">
  <a href="/connect/photos/{{ gallery.id }}/?start={{ next }}" class="orange">
  <span>Next &raquo;</span></a>
</div>


{% endifnotequal %}


<br class="imageboxes-break"/>



</div>
</td></tr></table>

{% endblock %}

templates/stockphoto/gallery_list.html
{% extends "connect/connect_base.html" %}
{% block title_detail %} Photo Galleries{% endblock %}

{% block post_nav %}
 <td width="700" valign="top">
                <div id="content">
                        <br><br>


<div style="font-size: 24px; margin-bottom: 5px;">Photo Galleries</div><br><br>

<div id="thumbnail-box">
  <div id="thumbnails">
    
{% for item in object_list %}
<table width="640" cellpadding="0" cellspacing="0" border="0">

<tr>
<td width="180">
      <a href="{{ item.id }}/?start=0">
        <img src="{{ item.first.thumburl }}" border="0" alt="{{ item.first.title }}" />
      </a>
</td>
<td width="460">
      <a href="{{ item.id }}/?start=0" class="blue"><span style="font-size: 24px; color: #2d9bfd;">{{ item.title }}</span></a>
</td>
</tr>
</table>
<br><br>
    {% endfor %}

  </div>
</div>

<br id="imageboxes-break"/>


{% if is_paginated %}

{% if has_previous %}
<a href="./?page={{ previous }}" class="orange">&laquo; Previous</a> |
{% endif %}
{% if has_next %}
<a href="./?page={{ next }}" class="orange">Next &raquo;</a>
{% endif %}
{% endif %}


</div>
</td>
</tr>
</table>

{% endblock %}

templates/stockphoto/photo_detail.html
{% extends "connect/connect_base.html" %}
{% block title_detail %} {{ object.gallery.title }} - {{ object.title }}


{% endblock %}

{% block post_nav %}


 <td width="700" valign="top">
                <div id="content">
                        <br><br>


<p id="breadcrumbs">
  <a href="../.." class="orange">Galleries</a> &raquo;
  <a href="../../{{ object.gallery.id }}/?start=0" class="orange">{{ object.gallery.title }}</a>
</p>
<br>
<a href="/connect/photos/upload/{{ object.gallery.id }}/" class="orange">Upload Your Own Photo</a>
<br><br>

<br><br>
{% if object.next %}
<div style="float: left">  
<a href="../{{ object.next.id }}/" class="orange">
  <span>&laquo;  Previous </span></a>
</div>
{% endif %}
{% if object.prev %}
<div style="float: right;">
  <a href="../{{ object.prev.id }}/" class="orange">
  <span>Next &raquo;</span></a>
</div>


{% endif %}

<br id="imageboxes-break"/>


<div id="large-image-box">
  <a href="{{ object.fullurl }}">
    <img src="{{ object.dispurl }}"  alt="{{ object.title }}" />
  </a>
  <div>
    {{ object.title }}<br>
	{% if object.photographer %}
		<i>posted by {{ object.photographer }}</i>
	{% endif %}
  </div>
</div>


</div>
</td>
</tr>
</table>

{% endblock %}

templates/stockphoto/uploadform.html
{% extends "connect/connect_base.html" %}

{% block title_detail %}
	Upload Your Photo
{% endblock %}

{% block post_nav %}

	<td width="700" valign="top">
		<div id="content">
			<br><br>
			
			<div style="font-size: 24px; margin-bottom: 5px;">Upload your Photo</div><br><br>
			
			<div id="welcome">
					
				<form action="/connect/photos/upload/{{ galleryId }}/" method="post"  enctype="multipart/form-data">
					<label for="id_name">Name:</label>&nbsp;&nbsp;<font color="#ff0000">{{ form.name.errors }}</font><br>
				        {{ form.name }}
					<br><br>
                                        <label for="id_title">Photo Title:</label>&nbsp;&nbsp;<font color="#ff0000">{{ form.title.errors }}</font><br>
                                        {{ form.title }}

					<br><br>
                                        <label for="id_file"></label>&nbsp;&nbsp;<font color="#ff0000">{{ form.file.errors }}</font><br>
                                        {{ form.file }}


					<br><br>
						

					<script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k=6LeXfr0SAAAAAKI1_SX-0JLqBI5X1xopLyW8HtV0{{ captcha_error }}"></script>
					
					<noscript>
						<iframe src="http://www.google.com/recaptcha/api/noscript?k=6LeXfr0SAAAAAKI1_SX-0JLqBI5X1xopLyW8HtV0{{ captcha_error }}" height="300" width="500" 
frameborder="0"></iframe><br>
						<textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
						<input type="hidden" name="recaptcha_response_field" value="manual_challenge">
					</noscript>
					<br>

					<p><input type="submit" value="Upload" /></p>
				</form>
			</div>
		
		</div>
	</td>
	</tr>
	</table>
			
{% endblock %}	